### ISSUE TITLE
Std430

### ISSUE THREAD

**Issue by LPGhatguy** [LPGhatguy/crevice#1]
It should be straightforward to extend the crate with support for std430 layout as well.

**Comment by benmkw** [comment]
As far as I'm aware the only difference is in struct and array handling where for std430 the alignment of the struct is just the maximum alignment of the members and for array its just the alignment of the member type. For std140 its additionally at least 16, so thats just one `if` that would be different. I could not yet find the code though https://github.com/LPGhatguy/crevice/search?q=max .

**Comment by LPGhatguy** [comment]
std140 struct alignment is currently [forced in the `AsStd140` derive macro](https://github.com/LPGhatguy/crevice/blob/346d323e61edbb3acae419693991e2a2a8848055/crevice-derive/src/lib.rs#L104). For deriving `AsStd430` we'll probably need to generate a const expression here that looks at the member types involved.

I think we will need separate primitive types for other layouts like std430. Currently, the minimum alignment forcing for matrices, for example, is just a regular associated constant. For example, [here is `Mat3`, whose alignment should (I think) be 12 in std430](https://github.com/LPGhatguy/crevice/blob/346d323e61edbb3acae419693991e2a2a8848055/src/std140/primitives.rs#L100).

**Comment by benmkw** [comment]
I think you need to look at the member types for std140 as well (for structs and also for arrays, only that for structs you take the max of the member types and for arrays there only is one member type), if one of them has an alignment or more than 16 bytes the whole thing (struct or array) needs to have larger alignment as well. How does glsl-layout handle that?

So this https://github.com/sotrh/learn-wgpu/pull/107/files is my current understanding of the situation/ rules extracted from university slides.

**Comment by LPGhatguy** [comment]
Ahah! You're right, based on the OpenGL 4.5 spec, section 7.6.2.2 on std140 layout:

> If the member is a structure, the base alignment of the structure is N, where N is the largest base alignment value of any of its members, and rounded up to the base alignment of a vec4.

I highly recommend this doc, it has very concise and clear rules for the layout that I apparently need to fix up a little in this crate: https://www.khronos.org/registry/OpenGL/specs/gl/glspec45.core.pdf#page=159

**Comment by benmkw** [comment]
yes exactly, thanks for the link :) 

Do you know if glsl-layout does this correctly?

**Comment by LPGhatguy** [comment]
I'm not sure. I _think_ glsl-layout does the right thing here, since it relies on Rust's `#[repr(align)]` attribute, which specifies minimum alignment, not alignment. Looking at the derive macro, however, the generated associated `Align` type is always `Align16`. I don't think that ends up mattering, but here is that code: https://github.com/rustgd/glsl-layout/blob/119f5ec524dca42403db2aa07569baa349793e9b/glsl-layout-derive/src/lib.rs#L46-L74

**Comment by LPGhatguy** [comment]
Ahahah, I see why this never came up before. None of the primitive types exposed in this crate have a base alignment above 16! If I'm reading the spec correctly, implementing the double precision variants of types should give us some types with a base alignment of 32 to test with.

**Comment by benmkw** [comment]
looking at the code it seems to me like everything in src is basically independent of std140/430 so that could maybe be renamed a bit and then it would only be the macro part that would expose another derive AsStd430?

**Comment by LPGhatguy** [comment]
It ends up being more complicated than that because of all of the trait and module name references! I put up a WIP PR at #12, also auto-linked above.

**Comment by benmkw** [comment]
Ok cool, feel free to ping me if you think I could help with some feedback/ ideas, otherwise I'll take a look anyways as time permits and if I think I could be helpful :)
