### ISSUE TITLE
structs need padding in std140 

### ISSUE THREAD

**Issue by benmkw** [LPGhatguy/crevice#16]
the following code

```rust
#[derive(AsStd140)]
struct MainUniform {
    b: Anon,
    c: f32,
}

#[derive(AsStd140)]
struct Anon {
    u: f32,
    v: f32,
}
```

yields:
```
| Offset | Name     | Size |
| ------ | -------- | ---- |
| 0      | _b_align | 0    |
| 0      | b        | 8    |
| 8      | _c_align | 0    |
| 8      | c        | 4    |

[src/main.rs:42] std::mem::size_of::<Std140MainUniform>() = 12
```

I think this is incorrect as struct have 16byte alignment and thus 8byte padding would need to be inserted as _c_align.

https://www.khronos.org/registry/OpenGL/specs/gl/glspec45.core.pdf#page=159
> If the member is a structure, the base alignment of the structure is N, where
N is the largest base alignment value of any of its members, and rounded
up to the base alignment of a vec4. The individual members of this substructure are then assigned offsets by applying this set of rules recursively,
where the base offset of the first member of the sub-structure is equal to the
aligned offset of the structure. The structure may have padding at the end;
the base offset of the member following the sub-structure is rounded up to
the next multiple of the base alignment of the structure.

**Comment by LPGhatguy** [comment]
Interesting, this seems like a bug! I'd love help developing a fix here. In general, the strategy I'd like to see is:

1. Write a small wgpu program using crevice to show the wrong behavior. Having a corresponding GLSL shader read the value and try to use it, or maybe just showing debug output in RenderDoc would be an easy demonstration that what we do today is wrong.

2. Write a test case, probably just a snapshot test like the others, and fix this behavior!

**Comment by benmkw** [comment]
```diff
diff --git a/crevice-derive/src/lib.rs b/crevice-derive/src/lib.rs
index 161241b..4e8889d 100644
--- a/crevice-derive/src/lib.rs
+++ b/crevice-derive/src/lib.rs
@@ -210,6 +210,12 @@ impl EmitOptions {
             quote!()
         };
 
+        // let struct_align: TokenStream = format!("structAlign{}", alignment_mod_name)
+        //     .parse()
+        //     .unwrap();
+
+        // const #struct_align: usize = #struct_alignment;
+
         quote! {
             #[allow(non_snake_case)]
             mod #alignment_mod_name {
@@ -220,7 +226,11 @@ impl EmitOptions {
 
             #[derive(Debug, Clone, Copy)]
             #type_layout_derive
-            #[repr(C)]
+            // TODO does not work?
+            // https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cdc2afea28acc81d32f3606360736635
+            // we actually need to take the maximum of 16 and the alignment of all members for std140...
+            // #[repr(C, algin(#struct_align))]
+            #[repr(C, align(16))]
             #visibility struct #generated_name #ty_generics #where_clause {
                 #( #generated_fields )*
             }
```

I think this is the place to fix the issue but it seems its not possible to use consts as inputs for the align attribute? Maybe you have an idea how to circumvent this restriction?

**Comment by benmkw** [comment]
@LPGhatguy I think this might actually work and seems to give the correct results after inspecting the type_layout manually at least.

```diff
diff --git a/crevice-derive/src/lib.rs b/crevice-derive/src/lib.rs
index 161241b..73d1313 100644
--- a/crevice-derive/src/lib.rs
+++ b/crevice-derive/src/lib.rs
@@ -210,18 +210,46 @@ impl EmitOptions {
             quote!()
         };
 
+        // this could go into crevice main as well and just be library structs
+        let alignment_struct = match min_struct_alignment {
+            0 => quote! {
+                #[repr(C, align(0))]
+                #[derive(Debug, Clone, Copy)]
+                pub struct Align0{}
+            },
+            16 => quote! {
+                #[repr(C, align(16))]
+                #[derive(Debug, Clone, Copy)]
+                pub struct Align16{}
+            },
+            _ => unreachable!(""),
+        };
+
+        let alignment_struct_member = match min_struct_alignment {
+            0 => quote! {
+                _alignment0_struct_member : #alignment_mod_name::Align0,
+            },
+            16 => quote! {
+                _alignment16_struct_member : #alignment_mod_name::Align16,
+            },
+            _ => unreachable!(""),
+        };
+
         quote! {
             #[allow(non_snake_case)]
             mod #alignment_mod_name {
                 use super::*;
 
                 #( #alignment_calculators )*
+
+                #alignment_struct
             }
 
             #[derive(Debug, Clone, Copy)]
             #type_layout_derive
             #[repr(C)]
             #visibility struct #generated_name #ty_generics #where_clause {
+                #alignment_struct_member
                 #( #generated_fields )*
             }
 ```

**Comment by LPGhatguy** [comment]
We _cannot_ use `#[repr(align)]` in Crevice -- it creates holes of initialized memory. The size of each prefix generated field should be able to account for the alignment needs of the next field, including a struct.

**Comment by benmkw** [comment]
The problem with the current approach as far as I can see is that you use the const fn to get the alignment and this only depends on the size of the basic primitives. But structs need 16byte alignment here and they are not really a primitive such that they get embedded without padding.

**Comment by LPGhatguy** [comment]
We can use `<<T as AsStd140>::Std140Type as Std140>::ALIGNMENT` to get the alignment of any type `T`, including a struct. This should be the strategy that we use to "align up" to the nearest multiple.

The entire reason why Crevice exists is because we cannot use `#[repr(align)]`. However, `#[repr(align)]` specifies _minimum_ alignment, so in your examples it would still be correct anyways.

I'd like to reiterate the process I asked us to follow for these kinds of issues:

1. Demonstrate the issue in a real program. wgpu and RenderDoc would be good here.
2. Design a fix: we cannot take advantage of `#[repr(align)]`
3. Snapshot tests!

**Comment by benmkw** [comment]
I would have provided the snapshots and test cases but I'm already 99% sure it is an issue because I have examples from university and re-read the specification and thus wanted to first figure out a way to fix the issues and then make sure they don't regress using the approach you suggested. If my explanations don't convince you that both std140 and std430 currently have issues I can also create testcases first because I don't yet see a way to fix it, although I definitely believe you that its possible 👍 

I forgot about the align restriction but this makes sense/ I remember now.

**Comment by benmkw** [comment]
```rust
                let offset_accumulation =
                    fields
                        .named
                        .iter()
                        .zip(&align_names)
                        .take(index)
                        .map(|(field, align_name)| {
                            let field_ty = &field.ty;
                            quote! {
                                offset += #align_name();
                                offset += ::std::mem::size_of::<#field_ty>();
                            }
                        });
```

I'm re reading this part which should ideally do what you said, get the alignment of the previous struct and then insert padding for the following float and the min_struct_alignment in struct_alignment should take care of making the structs alignment be at least 16, yet somehow it does not work.

Another issue I see is that the padding is always [u8] and thus alignment is never increased by the padding, in the case of a struct we need to increase the alignment of the outer structure though which is not possible by inserting [u8] padding. Maybe I'm missing something as proc-macro code is quite hard for me, although I like you comments which are helpful!

**Comment by LPGhatguy** [comment]
> I'm re reading this part which should ideally do what you said, get the alignment of the previous struct and then insert padding for the following float and the min_struct_alignment in struct_alignment should take care of making the structs alignment be at least 16, yet somehow it does not work.

What is the value of `<<T as AsStd140>::Std140Type as Std140Type>::ALIGNMENT` for a struct that appears to have invalid alignment? In std140, all structs should report >=16 for this, while in std430, there is no minimum requirement.

> Another issue I see is that the padding is always [u8] and thus alignment is never increased by the padding, in the case of a struct we need to increase the alignment of the outer structure though which is not possible by inserting [u8] padding.

It's alright if the struct itself has no alignment modifier. No part of Crevice nor code that copies our structs onto the GPU needs to use Rust's struct alignment mechanisms. This is okay because:

1. Allocations from graphics APIs should already be aligned for your data. If you're allocating a buffer and writing one struct, the alignment of that outer struct doesn't matter, and inner struct alignment should be handled by the proc macro.

2. When writing compound structs, we rely on the behavior of `{std140,std430}::Writer` and the alignment fields generated by the proc macro to correctly align members.

**Comment by benmkw** [comment]
> What is the value of <<T as AsStd140>::Std140Type as Std140Type>::ALIGNMENT for a struct that appears to have invalid alignment? In std140, all structs should report >=16 for this, while in std430, there is no minimum requirement.

Yes this is only an issue for std140, the ALIGNMENT appears to be correct, _c_align needs to be 8 bytes though because the rest of Anon needs to contain the padding. (`The structure may have padding at the end;
the base offset of the member following the sub-structure is rounded up to
the next multiple of the base alignment of the structure.`)
```rust
Std140MainUniform (size 12, alignment 4)
| Offset | Name     | Size |
| ------ | -------- | ---- |
| 0      | _b_align | 0    |
| 0      | b        | 8    |
| 8      | _c_align | 0    |
| 8      | c        | 4    |

Std140Anon (size 8, alignment 4)
| Offset | Name     | Size |
| ------ | -------- | ---- |
| 0      | _u_align | 0    |
| 0      | u        | 4    |
| 4      | _v_align | 0    |
| 4      | v        | 4    |

[src/main.rs:39] std::mem::size_of::<Std140MainUniform>() = 12
[src/main.rs:40] <<Std140MainUniform as AsStd140>::Std140Type as Std140>::ALIGNMENT = 16
[src/main.rs:41] <<Std140Anon as AsStd140>::Std140Type as Std140>::ALIGNMENT = 16
```

> It's alright if the struct itself has no alignment modifier.

Ah yes sure that sounds reasonable.

**Comment by ElectronicRU** [comment]
> > I'm re reading this part which should ideally do what you said, get the alignment of the previous struct and then insert padding for the following float and the min_struct_alignment in struct_alignment should take care of making the structs alignment be at least 16, yet somehow it does not work.
> 
> What is the value of `<<T as AsStd140>::Std140Type as Std140Type>::ALIGNMENT` for a struct that appears to have invalid alignment? In std140, all structs should report >=16 for this, while in std430, there is no minimum requirement.

Hey, looked at the macro with fresh eyes.
The issue is that, while calculating the alignment for the next struct member (f32 which is aligned to 4 bytes), we skip an important part of the spec:
> The structure may have padding at the end; the base offset of the member following the sub-structure is rounded up to the next multiple of the base alignment of the structure.
(ditto for arrays)
The fix I propose is implementing an alternative to size_of currently used in the macro - maybe call it inner_size? - that defaults to size_of, but struct derivation overrides it to align the size up to the alignment as well.
I believe this also fixes #17 .

**Comment by LPGhatguy** [comment]
> The fix I propose is implementing an alternative to size_of currently used in the macro - maybe call it inner_size? - that defaults to size_of, but struct derivation overrides it to align the size up to the alignment as well.
I believe this also fixes #17 .

This makes sense to me. Would you be up for trying to submit a failing test case and a fix for the macro? We haven't run into any issues using Crevice in our engine so far but I'm sure it's only a matter of time if there's an edge case like this.

**Comment by LPGhatguy** [comment]
> Btw, I've incidentally found an error in your offset calculation, I believe: in align functions you added the base field size to the offset, instead of the size of the corresponding Std140/430 type. I had to fix it, too - is it okay if I don't do a separate PR for that?

Yeah, that should be fine. Ideally I'd like to rig up a wgpu program that helps us validate that we got these things right to run against a real implementation instead of just a handful of folks interpreting the spec. I'll be pulling your branch into a game I work on to see if it affects anything we've done at least!

**Comment by ElectronicRU** [comment]
> > Btw, I've incidentally found an error in your offset calculation, I believe: in align functions you added the base field size to the offset, instead of the size of the corresponding Std140/430 type. I had to fix it, too - is it okay if I don't do a separate PR for that?
> 
> Yeah, that should be fine. Ideally I'd like to rig up a wgpu program that helps us validate that we got these things right to run against a real implementation instead of just a handful of folks interpreting the spec. I'll be pulling your branch into a game I work on to see if it affects anything we've done at least!

It's tricky to set up a proper test environment with wgpu, unfortunately - the library is, to put it kindly, verbose, and building GLSL shaders in tests is not ideal, either. Maybe when I have more time, I'll try to lend a hand with that.
