### ISSUE TITLE
Release 0.6.1 with no-std support

### ISSUE THREAD

**Issue by termhn** [LPGhatguy/crevice#31]
Hi! I noticed no-std support has been merged for a while but it's not on crates.io :( Could we do another release to get that in? :)

**Comment by LPGhatguy** [comment]
Thank you for the ping! I maintain a handful of things and sometimes it's hard to stay on top of cutting releases :c

I pushed up 0.7.0, since we had a few other things hanging out in the backlog.

**Comment by termhn** [comment]
I absolutely understand, haha. Thank you!
