### ISSUE TITLE
The WriteStd430 implementation for [T] resets the iterator

### ISSUE THREAD

**Issue by ironwaucka** [LPGhatguy/crevice#40]
https://github.com/LPGhatguy/crevice/blob/c38c0e3c765ab5f5360036dd345b206bfcda0b12/src/std430/traits.rs#L166

This appears to have been fixed for WriteStd140, but WriteStd430 seems to have been missed.

**Comment by LPGhatguy** [comment]
Oops, I didn't notice that this was still open! This was fixed in 342ca0ebd01db47d4249b8b4e95647c943c2cf22 and released in v0.10.0 last May.
