### ISSUE TITLE
Compilation fails without std feature

### ISSUE THREAD

**Issue by fiinnnn** [LPGhatguy/crevice#52]
Hey, just a heads up.
I was planning to use crevice for a rust-gpu project but I noticed compiling without the `std` feature currently results in compilation errors.

The usage of `String` here seems to cause it:
https://github.com/LPGhatguy/crevice/blob/0863f8508ab34f8625b4b2d29f5829b42969f7f1/src/glsl.rs#L60-L61
I might have time to look into this during the weekend.

**Comment by LPGhatguy** [comment]
Oops, sorry about this oversight!

We should add this to the CI matrix so that this doesn't regress.
