### ISSUE TITLE
Publish a new version?

### ISSUE THREAD

**Issue by expenses** [LPGhatguy/crevice#53]
I'm currently using `glam` 0.20 in my project. The version of this crate published to crates.io uses `glam` 0.19. As the glam version was updated in https://github.com/LPGhatguy/crevice/commit/f1c6a6c36972c9798e8ed93261838de017fe99af, it'd be great if you could publish a new version sometime :)

**Comment by LPGhatguy** [comment]
Done! Crevice 0.9.0 is published with the latest glam and nalgebra.
